# Generated by Django 5.1.4 on 2024-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='contact',
            field=models.CharField(max_length=15),
        ),
    ]
