# Generated by Django 5.1.4 on 2024-12-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_crud', '0002_alter_registerform_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registerform',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registerform',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registerform',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
