# Generated by Django 5.1.4 on 2024-12-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_crud', '0003_registerform_address_registerform_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='address',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerform',
            name='age',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerform',
            name='contact',
            field=models.CharField(default=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerform',
            name='email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registerform',
            name='name',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
