# Generated by Django 5.1.4 on 2024-12-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_crud', '0004_alter_registerform_address_alter_registerform_age_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registerform',
            table='dbs',
        ),
    ]
