# Generated by Django 5.1.4 on 2024-12-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_crud', '0005_alter_registerform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registerform',
            table=None,
        ),
    ]
